Drop table PRODUCT IF EXISTS ;

CREATE  TABLE PRODUCT(
    ID BIGINT NOT NULL,
    CREATIONDATE TIMESTAMP,
    DESCRIPTION VARCHAR(500),
    NAME VARCHAR(25) NOT NULL
);
ALTER TABLE PUBLIC.PRODUCT ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);


INSERT INTO PRODUCT(id,name ) values(1,'product1');
INSERT INTO PRODUCT(id,name ) values(2,'product2');
